import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to our Blog
        </h1>
        <p className={styles.description}>
          Get started with a new {' '}
          <code className={styles.code}>Blog</code>
        </p>

        <div className={styles.grid}>
          <a href="/blog/create" className={styles.card}>
            <h2>Create &rarr;</h2>
            <p>Create your own new blog now.</p>
          </a>

          <a href="/blog/read" className={styles.card}>
            <h2>Read &rarr;</h2>
            <p>Read blogs posted by other bloggers</p>
          </a>

          <a
            href="/blog/templates"
            className={styles.card}
          >
            <h2>Templates &rarr;</h2>
            <p>Discover templates to use for your blog</p>
          </a>

          <a
            href="/blog/drafts"
            className={styles.card}
          >
            <h2>Drafts &rarr;</h2>
            <p>
              A collection of your drafts in one place.
            </p>
          </a>
        </div>
      </main>
    </div>
  )
}
